version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: trade
      POSTGRES_PASSWORD: trade
      POSTGRES_DB: trade
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  trade-svc:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    command: ["python", "-m", "internal.queue.worker"]
    restart: on-failure

volumes:
  db-data:
